[project]
name = "mcp-client-llamaindex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index>=0.12.46",
    "llama-index-tools-mcp>=0.1.3",
    "mcp==1.9.0",
    "requests>=2.32.4",
]
